server:
  port: 8080

token:
  length: 8

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/link_shorter_db
    username: postgres
    password: 1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    drop-first: true
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml